name: LockThat
version: '1.0-SNAPSHOT'
main: dev.alexbright.lockthat.LockThat
api-version: 1.19
description: Creates and protects locked containers
commands:
  lock:
    description: Base command for LockThat

